name: Deploy MERN App to Local Runner

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
          
          # Install dependencies for Backend
          cd express.js_server
          npm install

          # Install dependencies for Frontend
          cd ../react.js_app
          npm install

          # Build Frontend
          npm run build

      - name: Deploy Backend
        run: |
          cd express.js_server
          npm start
